version: "3"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      - APP_RUNS_INSIDE_CONTAINER=1
    ports:
      - "${SSR_PORT}:${SSR_PORT_INTERNAL}"
    depends_on:
      - "postgres"
    networks:
      - common-network
    command: "npm run start"
  postgres:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
