const sentences = [
  "Prior to implementing the ArcGIS platform, when Ab… about landowners and their parcels of forestland",
  "An administrative assistant back at the office would convert these registries into Microsoft Excel files, and a forest engineer would verify all the data",
  "The majority of the data was then archived on paper",
  "The information was difficult to access and incon…nient to use when timely decisions had to be made",
  "To turn this into a fully digital process, Abastena first implemented Collector for ArcGIS",
  "Now, using Collector on a smartphone or tablet, one person can gather, record, and verify all the necessary information to determine what needs to be done to a parcel of land so it is eligible for FSC certification",
  "Collector makes it easy for technicians to fill in the data fields, and it traces the geometry of each parcel.",
  "All this information is then incorporated into ArcGIS Enterprise in real time, which helps forest landowners, producers, and managers immediately see what they need to do with their land to obtain and maintain FSC certification.",
];

const words = [
  "accessing",
  "ArcGIS",
  "Enterprise",
  "portal",
  "through",
  "forest",
  "landowners",
  "producers",
  "managers",
  "which",
  "management",
  "plan",
  "goes",
  "with",
  "which",
  "parcel",
  "land",
  "Having",
  "this",
  "information",
  "available",
  "ArcGIS",
  "Enterprise",
  "helps",
  "them",
  "ensure",
  "that",
  "their",
  "management",
  "plans",
  "adhere",
  "rules",
  "such",
  "preserving",
  "strengthening",
  "well-being",
  "local",
  "communities",
  "workers",
  "conserving",
  "restoring",
  "ecosystems",
  "Additionally",
  "users",
  "easily",
  "combine",
  "their",
  "interests",
  "priorities",
  "with",
  "sustainable",
  "forestry",
  "maintenance",
  "since",
  "information",
  "about",
  "each",
  "parcel",
  "forestland",
  "readily",
  "available",
  "ArcGIS",
  "Enterprise",
];

export { sentences, words };
